### ISSUE TITLE
Windows/Linux version?

### ISSUE THREAD

**Issue by jadbox** [filipeisho/breathe#1]
Would be awesome to get this onto other platforms :)

**Comment by amar-laksh** [comment]
KISS Solution for Linux:
imv breathe.gif

-> imv: https://github.com/eXeC64/imv (really lightweight viewer)

-> breathe.gif: https://quietkit.com/img/box-breathing-4x-v03.gif

-> Set it to a custom shortcut and press q to close window.

**Comment by amar-laksh** [comment]
> Would be awesome to get this onto other platforms :)

KISS Solution for Linux:
imv breathe.gif

-> imv: https://github.com/eXeC64/imv (really lightweight viewer)

-> breathe.gif: https://quietkit.com/img/box-breathing-4x-v03.gif

-> Set it to a custom shortcut and press q to close window.

**Comment by tryhardfifi** [comment]
That is definitely on the roadmap! I would first like to add some features to the macOS app to make it 100% usable and after that I can begin coding it up for linux/widows. In the meanwhile I am going to add your kiss solution to the readme @amar-laksh 😄

**Comment by sojusnik** [comment]
Would love to see this app as a [flatpak](https://flatpak.org/).
This would save time maintaining packages (.deb, .rpm etc.) for different distributions and make the installation very user-friendly.

**Comment by tryhardfifi** [comment]
I will take a look at it when I do the next release 😄

**Comment by sojusnik** [comment]
Just wanted to add that the best way to distribute flatpaks is via [Flathub](https://flathub.org).

**Comment by tryhardfifi** [comment]
Hi! Does any of you know what would be a good way of implementing breathe on linux and windows at the same time? I have never written any app for windows or linux... 
I don't know what you guys think (probably the best way for linux is not for windows and viceversa) but if I can kill two birds with one stone I would be very happy haha😊

**Comment by sojusnik** [comment]
I'm not a developer, but Qt seems to be a popular framework for cross platforms.

**Comment by sojusnik** [comment]
Maybe this will help too: https://news.ycombinator.com/item?id=24242412

**Comment by tryhardfifi** [comment]
Thanks @sojusnik ! That thread was really helpful. I am still looking for a good framework... As you already know breathe's most important feature is that the window always stays on top, so before deciding I need to check out all the solutions and see if they have a way to implement this feature.

**Comment by sojusnik** [comment]
Just wanted to know if there's some progress on a version for Linux? Can't wait to use your app on Ubuntu!

**Comment by tryhardfifi** [comment]
Hey! Sorry I have been very busy lately... Some time ago I made an app with Qt with the basics ([you can find the repo here](http://github.com/filipeisho/breathe-qt)). As I am no good in c++ what I did was to embed a js inside a QtWebView element and played around with the window settings so it always stayed on top and was anchored to a corner of the screen. The js code had a lot of bugs (using p5.js for the animations) and that was the last time I worked on it. 

As of now:
 - The circle doesn't resize when the window does
 - The animation breaks when you resize
 - The settings panel doesn't resize when the window does
 - I haven't found a way to change where the window is anchored from the js itself.

As you see the three first problems are easily fixable (the fourth might be a lot trickier). It goes without saying that if any of you want to help you are more than welcome to do so! 

If we haven't got any kind js expert here I will try to make some time this weekend to fix everything :)

**Comment by tryhardfifi** [comment]
Hey @sojusnik I am a couple of days late but I fixed the bugs that made the app unusable.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42777446/102499025-fbd28e00-407a-11eb-9023-b0e9d653d945.gif)

As you can see you still need to resize the window to change the settings, but everything else works 👍 

The only problem I am having right now is that I don't have a linux computer to compile the code (for it to run on linux)... Would you be willing to do so?

Edit: I just remembered you said you weren't a programmer, give me a couple of days so that I can find a workaround and I will compile it myself :)

**Comment by sojusnik** [comment]
Can't wait to test it out!

**Comment by tryhardfifi** [comment]
@sojusnik Hey! I just posted the (pre-)release on [here](https://github.com/filipeisho/breathe-qt/releases)! Bring any issues or feedback on that repo! Hope you like this first 'decent' linux version, take into account that it is still very rough tho...

**Comment by sojusnik** [comment]
Thanks! Already installed it and love it! But as you've said, it's very rough, already opening some issues over [here](https://github.com/filipeisho/breathe-qt/issues).
