### ISSUE TITLE
Adjust inhale, exhale and hold periods

### ISSUE THREAD

**Issue by sojusnik** [filipeisho/breathe#4]
Is it planned to provide settings for adjusting inhaling, exhaling, and both hold periods between those?

**Comment by tryhardfifi** [comment]
Yes! I have finished implementing this feature but I am waiting to finish other features to post the release. The latest commit has a settings panel where you can adjust everything, feel free to build the app yourself!

**Comment by tryhardfifi** [comment]
Hi! The new release (that has this feature) is already available! You can download it [here](https://github.com/filipeisho/breathe/releases)! I hope you like it!
